# Site settings
baseurl = "https://www.thinkforliving.com/"
languageCode = "en-us"
title = "ThinkForLiving"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Think For Living"
    description = "Connecting frontline staff with equipment reliably through Enablers"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "THINK FOR LIVING"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "kid.png"
        name = "#flattenthecurvehack"
        subtitle = "Connecting frontline staff with non profit service providers/equipment reliably through our Volunteers(Work in Progress)"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "REGISTER"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        sentence1 = "We are **ThinkForLiving**."
        sentence2 = "We care **lives**. We value **information**. We appreciate **contribution**. We cncourage **co-operation**."
        sentence3 = "We are building the platform for **requestor** to find and receive reosurces from **suppliers** in an easy and fast way with the help of **volunteers(enablers)**."
        sentence4 = "We are accelerating transaction of the **essential goods** to reach the people who are battling **Cov-19**."
        #right = "Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!"

        [params.about.button]
            text = "Download Source"
            link = "//github.com/thinkforliving/thinkforliving.github.io/archive/v0.1.zip"
            icon = "download"


    [params.contact]
        title = "Who We Are"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "A Non Profit Initiative! © Think For Living - 2020. All rights reserved."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social1]
            title = "Harshad"
            [[params.footer.social1.networks]]
                icon = "fa-linkedin"
                link = "//linkedin.com/in/harshadwankhede/"

            [[params.footer.social1.networks]]
                icon = "fa-github"
                link=  "//github.com/codeweft"

        [params.footer.social2]
            title = "Tina Zhang"
            [[params.footer.social2.networks]]
                icon = "fa-linkedin"
                link = "//linkedin.com/in/lu-zhang-380a99160"

            [[params.footer.social2.networks]]
                icon = "fa-github"
                link=  "//github.com/luzhangtina"

        [params.footer.social3]
            title = "Krunal Shah"
            [[params.footer.social3.networks]]
                icon = "fa-linkedin"
                link = "//linkedin.com/in/krunal-shah-00206913"

            [[params.footer.social3.networks]]
                icon = "fa-github"
                link=  "//github.com/thinkforliving"

        [params.footer.social4]
            title = "Shardul"
            [[params.footer.social4.networks]]
                icon = "fa-linkedin"
                link = "//linkedin.com/in/shardulsrivastava"

            [[params.footer.social4.networks]]
                icon = "fa-github"
                link=  "//github.com/shardulsrivastava"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
